In [186]:
import pandas as pd
from dotenv import load_dotenv
import os

import snowflake.connector

load_dotenv()

account= os.getenv("SNOWFLAKE_ACCOUNT")
user= os.getenv("SNOWFLAKE_USER")
password= os.getenv("SNOWFLAKE_PASSWORD")
warehouse= os.getenv("SNOWFLAKE_WAREHOUSE")
database= os.getenv("SNOWFLAKE_DATABASE")

connection= snowflake.connector.connect(account= account, user= user, password= password, warehouse= warehouse, database= database)

print(connection)
print("Connection successful:", connection.account)

<snowflake.connector.connection.SnowflakeConnection object at 0x000001F57D087610>
Connection successful: ui48522

In [187]:
cursor= connection.cursor()

cursor.execute('SELECT * FROM HOUSING_AFFORDABILITY.MARTS.MART_AFFORDABILITY')
mart= cursor.fetchall()

In [188]:
columns= [col[0] for col in cursor.description]

In [189]:
df_mart= pd.DataFrame(data= mart, columns= columns)

df_mart

,MONTH_DATE,CITY,COMPOSITE_BENCHMARK,COMPOSITE_BENCHMARK_CHANGE,MORTGAGE_ARREARS,LOAN_TO_INCOME_RATIO,DEBT_SERVICE_RATIO,MORTGAGE_RATE_5YRS_FIXED,MORTGAGE_RATE_5YRS_VARIABLE,POLICY_RATE,POLICY_RATE_CHANGE,BENCHMARK_TO_RATE_RATIO,BENCHMARK_YOY_PERCENTAGE_CHANGE
0,2018-01-01,CALGARY,420700,NaN,20.0,280.79,16.90,3.19,2.55,1.25,NaN,336560.00,NaN
1,2018-02-01,CALGARY,423100,2400.0,NaN,NaN,NaN,3.24,2.50,1.25,0.00,338480.00,NaN
2,2018-03-01,CALGARY,425500,2400.0,NaN,NaN,NaN,3.24,2.50,1.25,0.00,340400.00,NaN
3,2018-04-01,CALGARY,426800,1300.0,20.0,267.87,16.17,3.24,2.50,1.25,0.00,341440.00,NaN
4,2018-05-01,CALGARY,426900,100.0,NaN,NaN,NaN,3.34,2.45,1.25,0.00,341520.00,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
779,2025-10-01,WINNIPEG,379200,-1000.0,21.0,NaN,18.77,4.14,3.90,2.25,-0.25,168533.33,5.27
780,2025-11-01,WINNIPEG,378300,-900.0,NaN,NaN,NaN,4.04,3.75,2.25,0.00,168133.33,5.29
781,2025-12-01,WINNIPEG,380400,2100.0,NaN,NaN,NaN,4.14,3.75,2.25,0.00,169066.67,6.23
782,2026-01-01,WINNIPEG,382100,1700.0,NaN,NaN,NaN,4.14,3.70,2.25,0.00,169822.22,5.55
783,2026-02-01,WINNIPEG,383800,1700.0,NaN,NaN,NaN,3.99,3.70,2.25,0.00,170577.78,3.03

In [190]:
df_mart.describe()

,COMPOSITE_BENCHMARK,COMPOSITE_BENCHMARK_CHANGE,MORTGAGE_ARREARS,LOAN_TO_INCOME_RATIO,DEBT_SERVICE_RATIO,MORTGAGE_RATE_5YRS_FIXED,MORTGAGE_RATE_5YRS_VARIABLE,POLICY_RATE,POLICY_RATE_CHANGE,BENCHMARK_TO_RATE_RATIO,BENCHMARK_YOY_PERCENTAGE_CHANGE
count,7.840000e+02,776.000000,256.000000,200.000000,256.000000,784.000000,784.000000,784.000000,776.000000,7.840000e+02,688.000000
mean,5.830120e+05,1780.541237,17.375000,290.581200,17.822812,3.595102,3.554592,2.234694,0.010309,7.507080e+05,5.613038
std,2.757632e+05,10456.020101,3.495656,16.871048,1.707854,1.110508,1.649793,1.653518,0.251236,1.034545e+06,8.978533
min,2.664000e+05,-49700.000000,12.000000,267.870000,15.720000,1.690000,1.300000,0.250000,-1.500000,6.610000e+04,-18.390000
25%,3.674750e+05,-2500.000000,14.000000,279.010000,16.260000,2.690000,2.250000,0.500000,0.000000,1.602000e+05,-0.267500
50%,5.050000e+05,1100.000000,18.500000,284.110000,17.005000,3.565000,2.950000,1.750000,0.000000,2.425270e+05,4.755000
75%,7.147250e+05,5700.000000,20.250000,306.740000,19.570000,4.590000,5.010000,3.750000,0.000000,1.150400e+06,10.050000
max,1.279800e+06,75100.000000,22.000000,318.900000,20.600000,5.720000,6.300000,5.000000,1.000000,5.119200e+06,38.750000

In [191]:
df_mart.shape

(784, 13)

In [192]:
df_mart.dtypes

MONTH_DATE                          object
CITY                                object
COMPOSITE_BENCHMARK                  int64
COMPOSITE_BENCHMARK_CHANGE         float64
MORTGAGE_ARREARS                   float64
LOAN_TO_INCOME_RATIO               float64
DEBT_SERVICE_RATIO                 float64
MORTGAGE_RATE_5YRS_FIXED           float64
MORTGAGE_RATE_5YRS_VARIABLE        float64
POLICY_RATE                        float64
POLICY_RATE_CHANGE                 float64
BENCHMARK_TO_RATE_RATIO            float64
BENCHMARK_YOY_PERCENTAGE_CHANGE    float64
dtype: object

In [193]:
df_mart.head(100)

,MONTH_DATE,CITY,COMPOSITE_BENCHMARK,COMPOSITE_BENCHMARK_CHANGE,MORTGAGE_ARREARS,LOAN_TO_INCOME_RATIO,DEBT_SERVICE_RATIO,MORTGAGE_RATE_5YRS_FIXED,MORTGAGE_RATE_5YRS_VARIABLE,POLICY_RATE,POLICY_RATE_CHANGE,BENCHMARK_TO_RATE_RATIO,BENCHMARK_YOY_PERCENTAGE_CHANGE
0,2018-01-01,CALGARY,420700,NaN,20.0,280.79,16.90,3.19,2.55,1.25,NaN,336560.00,NaN
1,2018-02-01,CALGARY,423100,2400.0,NaN,NaN,NaN,3.24,2.50,1.25,0.0,338480.00,NaN
2,2018-03-01,CALGARY,425500,2400.0,NaN,NaN,NaN,3.24,2.50,1.25,0.0,340400.00,NaN
3,2018-04-01,CALGARY,426800,1300.0,20.0,267.87,16.17,3.24,2.50,1.25,0.0,341440.00,NaN
4,2018-05-01,CALGARY,426900,100.0,NaN,NaN,NaN,3.34,2.45,1.25,0.0,341520.00,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2025-12-01,CALGARY,554800,-2900.0,NaN,NaN,NaN,4.14,3.75,2.25,0.0,246577.78,-3.24
96,2026-01-01,CALGARY,555500,700.0,NaN,NaN,NaN,4.14,3.70,2.25,0.0,246888.89,-3.24
97,2026-02-01,CALGARY,562000,6500.0,NaN,NaN,NaN,3.99,3.70,2.25,0.0,249777.78,-2.72
98,2018-01-01,EDMONTON,345000,NaN,20.0,280.79,16.90,3.19,2.55,1.25,NaN,276000.00,NaN
99,2018-02-01,EDMONTON,348900,3900.0,NaN,NaN,NaN,3.24,2.50,1.25,0.0,279120.00,NaN

In [194]:
df_mart.to_excel('..\data\processed\df_mart.xlsx')

In [195]:
df_mart['MONTH_DATE']= pd.to_datetime(df_mart['MONTH_DATE'])

start_date = '2019-01-01'
end_date = '2024-01-01'

df_model= df_mart.loc[(df_mart['MONTH_DATE'] >= start_date) & (df_mart['MONTH_DATE'] <= end_date)]

In [196]:
df_model.shape

(488, 13)

In [197]:
df_model['DEBT_SERVICE_RATIO'].isna().sum()

np.int64(320)

In [198]:
df_model= df_model.dropna(subset=['DEBT_SERVICE_RATIO'])

df_model.shape

(168, 13)

In [199]:
city_display_map = {
    'CALGARY': 'Calgary',
    'EDMONTON': 'Edmonton',
    'GREATER_TORONTO': 'Toronto',
    'GREATER_VANCOUVER': 'Vancouver',
    'HALIFAX_DARTMOUTH': 'Halifax',
    'MONTREAL_CMA': 'Montreal',
    'OTTAWA': 'Ottawa',
    'WINNIPEG': 'Winnipeg'
}

In [200]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, root_mean_squared_error

results= []
models = {}

for city in df_model['CITY'].unique():
    df_city= df_model.loc[df_model['CITY'] == city]
    
    X= df_city[['POLICY_RATE']]
    Y= df_city['COMPOSITE_BENCHMARK']
    model= LinearRegression()
    model.fit(X, Y)
    policy_coef= model.coef_[0]
    y_pred= model.predict(X)
    r2= r2_score(Y, y_pred)
    rmse= root_mean_squared_error(Y, y_pred)
    results.append({
        'CITY': city,
        'POLICY_COEF': round(policy_coef, 2),
        'R2': round(r2, 4),
        'RMSE': round(rmse, 2),
    })
    models[city] = model

df_results= pd.DataFrame(results)
df_results['CITY_DISPLAY'] = df_results['CITY'].map(city_display_map)
df_results

                CITY  POLICY_COEF      R2       RMSE CITY_DISPLAY
0            CALGARY     22209.47  0.5519   36175.72      Calgary
1           EDMONTON      2008.74  0.0380   18281.38     Edmonton
2    GREATER_TORONTO     20306.01  0.0611  143871.35      Toronto
3  GREATER_VANCOUVER     31132.60  0.2020  111876.22    Vancouver
4  HALIFAX_DARTMOUTH     26202.55  0.2506   81912.94      Halifax
5       MONTREAL_CMA     16373.41  0.1765   63926.27     Montreal
6             OTTAWA      9793.44  0.0424   84106.37       Ottawa
7           WINNIPEG      5529.33  0.1153   27688.19     Winnipeg

In [201]:
import statsmodels.formula.api as smf

significance_results= []

for city in df_model['CITY'].unique():

    df_city= df_model.loc[df_model['CITY'] == city]
    
    model= smf.ols(
        formula= 'COMPOSITE_BENCHMARK ~ POLICY_RATE',
        data= df_city
    ).fit()
    
    significance_results.append({
        'CITY': city,
        'POLICY_RATE_P': model.pvalues['POLICY_RATE']
    })
    
df_significance_results= pd.DataFrame(significance_results)
df_significance_results

                CITY  POLICY_RATE_P
0            CALGARY       0.000114
1           EDMONTON       0.397395
2    GREATER_TORONTO       0.279953
3  GREATER_VANCOUVER       0.040977
4  HALIFAX_DARTMOUTH       0.020817
5       MONTREAL_CMA       0.057912
6             OTTAWA       0.370372
7           WINNIPEG       0.132091

In [202]:
df_results = df_results.merge(df_significance_results, on='CITY')

In [203]:
# What if policy rate went to 5%?
new_data = pd.DataFrame({
    'POLICY_RATE': [5.0],
})

predict_result= []

for city in models:
    predict_result.append({
        'CITY': city,
        'PREDICTED_BENCHMARK': models[city].predict(new_data)[0]
    })
    
df_predict_result= pd.DataFrame(predict_result)
df_predict_result

                CITY  PREDICTED_BENCHMARK
0            CALGARY         5.317998e+05
1           EDMONTON         3.661738e+05
2    GREATER_TORONTO         1.032113e+06
3  GREATER_VANCOUVER         1.146703e+06
4  HALIFAX_DARTMOUTH         5.012124e+05
5       MONTREAL_CMA         4.951297e+05
6             OTTAWA         5.816089e+05
7           WINNIPEG         3.324451e+05

In [204]:
df_results = df_results.merge(df_predict_result, on='CITY')

In [206]:
from snowflake.connector import pandas_tools

cursor.execute('''CREATE OR REPLACE TABLE HOUSING_AFFORDABILITY.MARTS.MART_MODEL_SKTLEARN (
                    CITY TEXT,
                    POLICY_COEF FLOAT,
                    R2 FLOAT,
                    RMSE FLOAT,
                    CITY_DISPLAY TEXT,
                    POLICY_RATE_P FLOAT,
                    PREDICTED_BENCHMARK FLOAT
                )''')

pandas_tools.write_pandas(connection, df_results, "MART_MODEL_SKTLEARN", schema= "MARTS")

(True,
 1,
 8,
 [('snowpark_temp_stage_ry978vxf51/file0.txt',
   'LOADED',
   8,
   8,
   1,
   0,
   None,
   None,
   None,
   None)])

In [208]:
connection.close()